---
name: Repository keepalive

on:
  schedule:
    - cron: 0 0 */25 * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  keepalive:
    name: Repository keepalive
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Repository keepalive
        uses: gautamkrishnar/keepalive-workflow@v2
